#!/bin/bash

sub_script="condor.sub"

cwd=`pwd -P`
base_dir="$cwd"

#----------------------------------------------------------------------------------------------------

function RunList()
{
	for dir in ${list[*]}
	do
		eos_dir="/eos/cms/store/group/phys_pps/ppxz/$dir"
		rm -rf "$eos_dir/ntuple.root"

		(
			echo ""
			echo "dir=output/$dir"
			echo "queue"
		) >> "$sub_script"
	done
}

#----------------------------------------------------------------------------------------------------

(
	echo "executable = $base_dir/\$(dir)/job"
	echo "arguments = \$(ClusterId) \$(ProcId) \\\"\$(dir)\\\""
	echo "output = $base_dir/\$(dir)/out"
	echo "error = $base_dir/\$(dir)/err"
	echo "log = $base_dir/condor.log"

	echo "+MaxRuntime = 14400" # in s

	#echo "+JobBatchName = \"$output_dir\""

	echo "requirements = (OpSysAndVer =?= \"CentOS7\")"

) > "$sub_script"

#----------------------------------------------------------------------------------------------------

list=(
	version7/Z/m_X_840/xangle_140/2017_postTS2
	version7/Z/m_X_1080/xangle_120/2017_preTS2
	version7/gamma/m_X_840/xangle_140/2017_postTS2_opt_v1_simu_reco
)

RunList

echo "To submit:"
echo "    condor_submit \"$sub_script\""
